

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-ingress
  namespace: kasadara
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: www.softwarestack.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: python-application-service
                port:
                  number: 80


